export const BANNED_PHRASES = [
  "2g1c",
  "4chan",
  "baccarat",
  "betting",
  "betting odds",
  "betting line",
  "blackjack",
  "casino",
  "craps",
  "gamble",
  "gambling",
  "online gambling",
  "poker",
  "roulette",
  "slot machine",
  "texas hold'em",
  "a2m ",
  "acrotomophilia",
  "adult ",
  "amateur",
  "anal",
  "anilingus",
  "annie sprinkle",
  "anus",
  "apple bong howto",
  "are idiots",
  "arsehole",
  "aryan",
  "asexual",
  "asian babe",
  "ass",
  "asshole",
  "assmunch",
  "auto erotic",
  "autoerotic",
  "babes in toyland",
  "babeland",
  "baby batter",
  "baby chowder",
  "ball gravy",
  "ball sack",
  "ball gag",
  "ball kicking",
  "ball licking",
  "ball sucking",
  "bangbros",
  "bareback",
  "barely legal",
  "barenaked ladies",
  "bastard",
  "bastardo",
  "bastinado",
  "bbw",
  "bdsm ",
  "beaner",
  "bearded clam",
  "beaver cleaver",
  "beaver lips",
  "behind the green door",
  "bestiality",
  "betty dodson",
  "bi curious",
  "bianca beauchamp",
  "big black",
  "big knockers ",
  "big tits",
  "bimbo",
  "bimbos",
  "birdlock",
  "bisexual",
  "bitch",
  "black cock",
  "blonde action ",
  "blonde on blonde action ",
  "blood play",
  "blow",
  "blow j",
  "blow your l",
  "bludgeon",
  "blue waffle",
  "blumpkin",
  "bollocks",
  "bondage ",
  "boner",
  "boob",
  "booty call",
  "breast",
  "brown showers",
  "brunette action",
  "bugger",
  "bukkake",
  "bulldyke",
  "bullet vibe",
  "bumming",
  "bung hole",
  "bunghole",
  "busty",
  "butt",
  "butthole",
  "buttcheeks",
  "buttcrack",
  "buttocks",
  "camel toe",
  "camgirl",
  "camslut",
  "camwhore",
  "carnage",
  "carol queen",
  "carpet muncher",
  "carpetmuncher",
  "chastity belt",
  "chink",
  "chocolate rosebuds",
  "chrissie wunna",
  "church of satan",
  "circlejerk",
  "cleveland steamer",
  "clit",
  "clitoral",
  "clitoris",
  "clitoritis",
  "clover clamps",
  "clusterfuck",
  "cocaine",
  "cock",
  "cocks",
  "commie",
  "consensual intercourse",
  "coprolagnia",
  "coprophilia ",
  "coprophagia",
  "cornhole",
  "cory silverberg",
  "courtney trouble",
  "crack",
  "cream pie",
  "creampie",
  "crossdresser",
  "cuckold",
  "cum",
  "cumming",
  "cunt",
  "cunnilingus",
  "dago",
  "darkie",
  "date rape",
  "daterape",
  "deep throat",
  "deepthroat",
  "dick",
  "diddy ride",
  "dildo",
  "dirty pillows",
  "dirty sanchez",
  "disembowel",
  "dismember",
  "dog style",
  "doggie style",
  "doggiestyle",
  "doggy style",
  "doggystyle",
  "dolcett",
  "domination",
  "dominatrix",
  "dommes",
  "donkey punch",
  "dothead",
  "double dong",
  "double penetration",
  "dp action",
  "ducky doolittle",
  "dutch oven",
  "dyke",
  "eat my ass",
  "ecchi",
  "ecstasy",
  "ejaculation",
  "electrotorture",
  "erection",
  "erotic",
  "erotism",
  "escort",
  "ethical slut",
  "eunuch",
  "excrement",
  "extreme elvis",
  "fag",
  "faggot",
  "faggot",
  "fantasies",
  "fapserver",
  "fascist",
  "fecal",
  "felch",
  "fellatio",
  "feltch",
  "femdom",
  "female desperation",
  "female squirting",
  "feminazi",
  "fetish",
  "figging",
  "filthy sanchez",
  "fingering ",
  "fisting",
  "five knuckle shuffle",
  "flick the bean",
  "foot fetish",
  "footjob",
  "foreplay",
  "fornicate",
  "foursome",
  "freeones",
  "frotting",
  "fuck",
  "fuck buttons",
  "fudge packer",
  "fudgepacker",
  "futanari",
  "g-spot",
  "g-string",
  "gang bang",
  "gay boy",
  "gay dog",
  "gay man",
  "gay men",
  "gay sex",
  "genitals",
  "get my sister",
  "giant cock",
  "ginger lynne",
  "girl on",
  "girl on top",
  "girls gone wild",
  "goat.se",
  "goatcx",
  "goatse",
  "gokkun",
  "golden shower",
  "golliwog",
  "goo girl",
  "good poop",
  "goodpoop",
  "goodvibes",
  "google is evil",
  "gook",
  "goregasm",
  "got my sister",
  "greaser",
  "gringo",
  "grope",
  "group sex",
  "gtfo",
  "guro",
  "hairy",
  "hand job",
  "handjob",
  "happy slapping video",
  "hard core",
  "hardcore",
  "hate",
  "hebe",
  "hedop",
  "hentai",
  "hermaphrodite",
  "heroin",
  "heroin",
  "heterosexual",
  "hickey",
  "holdem",
  "homoerotic",
  "homosexual",
  "honkey",
  "honky",
  "hookup",
  "hooker",
  "hot chick",
  "hottie",
  "how to commit genocide",
  "how to commit suicide",
  "how to kill",
  "how to murder",
  "how to torture",
  "huge fat",
  "humping",
  "hustler",
  "i hate",
  "impalement",
  "incest",
  "injun",
  "insertions",
  "interracial",
  "jack off",
  "jackie strano",
  "jacobs ladder piercing",
  "jail bait",
  "jailbait",
  "jenna jameson",
  "jerk off ",
  "jesse jane",
  "jizz",
  "jigaboo",
  "jiggaboo",
  "jiggerboo",
  "john holmes",
  "jordan capri",
  "juggs",
  "kama",
  "kamasutra",
  "kike",
  "kinbaku",
  "kinky",
  "kinkster",
  "kinsey institute",
  "kkk",
  "knobbing ",
  "ku klux klan",
  "labia",
  "latina",
  "leather restraint",
  "leather straight jacket",
  "lemon party",
  "lemonparty",
  "lesbian",
  "licked",
  "linda lovelace",
  "lindsay lohan",
  "lingerie",
  "lolita",
  "lovemaking",
  "lovers",
  "lsd",
  "madison young",
  "make me come",
  "making love",
  "male squirting",
  "marijuana",
  "marijuana",
  "masturbate ",
  "mature",
  "mdma",
  "meats",
  "menage a trois",
  "merkin",
  "miki sawaguchi",
  "milf",
  "missionary",
  "missionary position",
  "money shot",
  "motherfucker",
  "mound of venus",
  "mr hands",
  "muff diver",
  "muffdiving",
  "murder",
  "murder",
  "naked",
  "nambla",
  "naughty",
  "nawashi",
  "nazi",
  "necrophilia",
  "negro",
  "neonazi",
  "new pornographers",
  "nicky hilton",
  "nig nog",
  "nigga",
  "nigger",
  "nimphomania",
  "nina hartley",
  "nipple",
  "nipples",
  "nonconsent",
  "nsfw images",
  "nude",
  "nut butter",
  "nympho",
  "nymphomania",
  "octopussy",
  "octopussoir",
  "omorashi",
  "one cup two girls ",
  "one guy one jar",
  "oral",
  "oral sex",
  "orgy",
  "orgasm",
  "outercourse",
  "paedophile",
  "pamela anderson",
  "pansy",
  "panty",
  "panties",
  "paris hilton",
  "paris whitney hilton",
  "pecker",
  "pedobear",
  "pedophile",
  "peep show",
  "pegging",
  "penetration",
  "penis",
  "penthouse",
  "pervert",
  "philip kindred dick",
  "phone sex",
  "pickaninny",
  "piece of shit",
  "pinko",
  "piss",
  "piss pig",
  "pissing",
  "pisspig",
  "playboy",
  "pleasure chest",
  "pole smoker",
  "ponyplay",
  "poof",
  "poofter",
  "poop chute",
  "poopchute",
  "porn",
  "pr0n",
  "pre teen",
  "preteen",
  "prince albert piercing",
  "prolapsed",
  "prostitute",
  "pthc",
  "pubes",
  "pubic",
  "puppy play",
  "pussy",
  "queaf",
  "queef",
  "quickie",
  "quim",
  "r@ygold",
  "raghead",
  "raging boner",
  "rape",
  "raping",
  "rapist",
  "rapping women",
  "rectum",
  "redtube",
  "redskin",
  "renob",
  "retard",
  "reverse cowgirl",
  "rimjob",
  "rimming",
  "roman shower",
  "ron jeremy",
  "rosy palm",
  "rosy palm and her 5 sisters",
  "rule 34",
  "russian brides",
  "rusty trombone",
  "s and m",
  "s&m",
  "sadie lune",
  "sadism",
  "sadist",
  "sambo",
  "sasha grey",
  "sausage party",
  "savage love",
  "scat",
  "schlong",
  "schoolgirl",
  "schoolboy",
  "scissoring",
  "seduced",
  "seductive",
  "semen",
  "servitude",
  "serviture",
  "sex",
  "sexo",
  "sexy",
  "sexual reproduction",
  "shanna katz",
  "shar rednaur",
  "shauna grant",
  "shaved beaver",
  "shaved pussy",
  "shaved fish",
  "shay lauren",
  "shemale",
  "shibari",
  "shit",
  "shocker",
  "shota",
  "shrimping",
  "sissy",
  "size queen",
  "sjambok",
  "skank",
  "slanteye",
  "sleazy d",
  "slit",
  "slut",
  "smells like teen spirit ",
  "smut",
  "snatch",
  "snowballing",
  "sodomize",
  "sodomy",
  "spank",
  "speculum",
  "sperm",
  "spic",
  "spooge",
  "spook",
  "spread legs",
  "spunky teens",
  "squirt",
  "stab",
  "stickam girl",
  "stileproject",
  "stormfront",
  "strap on",
  "strapon",
  "strappado",
  "strip club",
  "style doggy",
  "submissive",
  "submission",
  "suck",
  "sucks",
  "suicide girls",
  "sultry men",
  "sultry women",
  "susie bright",
  "swastika",
  "swinger",
  "taboo 2",
  "tainted love",
  "taste my",
  "tea bagging",
  "teen",
  "tentacle",
  "testicle",
  "thong",
  "threesome",
  "throating",
  "tied up",
  "tight white",
  "tit",
  "titties ",
  "titty",
  "tongue in a",
  "tosser",
  "towelhead",
  "traci lords",
  "tranny",
  "transexual",
  "transgender",
  "tribadism",
  "trisexual",
  "tub girl",
  "tubgirl",
  "turd",
  "tushy",
  "twat",
  "twink",
  "twinkie",
  "two girls ",
  "two girls one cup",
  "undressing",
  "upskirt",
  "urethra play",
  "urophilia",
  "vagina",
  "vagisil",
  "vanilla rosebuds",
  "venus mound",
  "vibrator",
  "violet blue",
  "violet ray",
  "violet wand",
  "vivid",
  "vorarephilia",
  "voyeur",
  "vulva",
  "wank",
  "wartenberg pinwheel",
  "wartenberg wheel",
  "watersports",
  "webcam",
  "wet dream",
  "wetback",
  "white power",
  "whore",
  "wigger",
  "women rapping",
  "wop",
  "wrapping men",
  "wrapping women",
  "wrinkled starfish",
  "wtf",
  "xx",
  "yaoi",
  "yellow showers",
  "yiffy",
  "zoophilia",
] as const;
